import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, ImagePlus, Loader2, Save } from 'lucide-react';
import { createCourseBundle, getCourseBundles, getCourses, updateCourseBundle, uploadFile } from '@/api/client';
import type { Course, CourseBundle } from '@/types';

export default function BundleForm() {
  const { id } = useParams(); const isNew = !id; const navigate = useNavigate(); const qc = useQueryClient();
  const { data: bundles } = useQuery({ queryKey: ['course-bundles'], queryFn: getCourseBundles });
  const { data: coursesData } = useQuery({ queryKey: ['bundle-courses'], queryFn: () => getCourses({ fields: JSON.stringify(['name','title','published']), filters: JSON.stringify({ published: 1 }), limit_page_length: 0 }) });
  const bundle = (bundles as CourseBundle[] | undefined)?.find(item => item.name === id);
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [image, setImage] = useState(''); const [price, setPrice] = useState(''); const [discount, setDiscount] = useState(''); const [selected, setSelected] = useState<string[]>([]);
  useEffect(() => { if (bundle) { setTitle(bundle.title); setDescription(bundle.description); setImage(bundle.image || ''); setPrice(String(bundle.price)); setDiscount(String(bundle.discount_percentage || '')); setSelected(bundle.courses.map(c => c.name)); } }, [bundle]);
  const save = useMutation({ mutationFn: (published: number) => { const payload = { title, description, image, price: Number(price), currency: 'ETB', discount_percentage: Number(discount || 0), published, courses: selected }; return isNew ? createCourseBundle(payload) : updateCourseBundle(id!, payload); }, onSuccess: () => { qc.invalidateQueries({ queryKey: ['course-bundles'] }); navigate('/bundles'); } });
  const courses = (Array.isArray(coursesData) ? coursesData : (coursesData as any)?.data || []) as Course[];
  const upload = async (file?: File) => { if (!file) return; const result = await uploadFile(file, { folder: 'Home' }); setImage(result.file_url); };
  const toggle = (name: string) => setSelected(list => list.includes(name) ? list.filter(item => item !== name) : [...list, name]);
  if (!isNew && !bundle) return <div className="py-12 text-center text-gray-500"><Loader2 className="animate-spin inline w-5 h-5 mr-2" />Loading bundle…</div>;
  return <form onSubmit={e => { e.preventDefault(); save.mutate(1); }} className="max-w-4xl space-y-6"><div className="flex justify-between items-start"><div><button type="button" onClick={() => navigate('/bundles')} className="text-sm text-gray-500 flex gap-1 items-center mb-2"><ArrowLeft className="w-4 h-4" /> Bundles</button><h1 className="font-heading text-2xl font-bold">{isNew ? 'Create Course Bundle' : 'Edit Course Bundle'}</h1></div><div className="flex gap-2"><button type="button" disabled={save.isPending} onClick={() => save.mutate(0)} className="px-4 py-2 border rounded-lg text-sm">Save Draft</button><button type="submit" disabled={save.isPending} className="px-4 py-2 rounded-lg bg-dark text-white text-sm flex gap-2 items-center"><Save className="w-4 h-4" />{bundle?.published ? 'Update' : 'Publish'}</button></div></div>
    {save.error && <p className="p-3 rounded-lg bg-red-50 text-red-700 text-sm">{(save.error as any)?.message || 'Could not save the bundle.'}</p>}
    <div className="admin-card space-y-5"><div><label className="block text-sm font-medium mb-1">Title *</label><input required value={title} onChange={e => setTitle(e.target.value)} className="w-full px-3 py-2 border rounded-lg" placeholder="Complete SPMU Program" /></div><div><label className="block text-sm font-medium mb-1">Description</label><textarea value={description} onChange={e => setDescription(e.target.value)} rows={4} className="w-full px-3 py-2 border rounded-lg" placeholder="Explain why students should choose this bundle." /></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label className="block text-sm font-medium mb-1">Sale price (ETB) *</label><input required min="0" type="number" value={price} onChange={e => setPrice(e.target.value)} className="w-full px-3 py-2 border rounded-lg" /></div><div><label className="block text-sm font-medium mb-1">Discount %</label><input min="0" max="99" type="number" value={discount} onChange={e => setDiscount(e.target.value)} className="w-full px-3 py-2 border rounded-lg" /></div></div>
      <div><label className="block text-sm font-medium mb-2">Bundle image</label><div className="flex items-center gap-3">{image && <img src={image} alt="Preview" className="h-16 w-28 object-cover rounded-lg" />}<label className="cursor-pointer flex items-center gap-2 px-3 py-2 border rounded-lg text-sm"><ImagePlus className="w-4 h-4" />Upload image<input className="hidden" type="file" accept="image/*" onChange={e => void upload(e.target.files?.[0])} /></label>{image && <button type="button" onClick={() => setImage('')} className="text-sm text-red-600">Remove</button>}</div></div></div>
    <div className="admin-card"><h2 className="font-heading font-semibold">Included published courses *</h2><p className="text-sm text-gray-500 mt-1 mb-4">Choose at least two courses. The list is saved with every purchase.</p><div className="divide-y">{courses.map(course => <label key={course.name} className="flex items-center gap-3 py-3 cursor-pointer"><input type="checkbox" checked={selected.includes(course.name)} onChange={() => toggle(course.name)} /><span className="text-sm font-medium">{course.title}</span></label>)}</div>{courses.length === 0 && <p className="text-sm text-gray-500">No published courses are available yet.</p>}</div>
  </form>;
}
