# -*- coding: utf-8 -*-
"""Delta SPMU — Ombré Brows Artistry exam bank.

Per-lesson multiple-choice quizzes transcribed from the official
"Delta aesthetics training exam bank" (SPMU module). Single source of truth,
consumed by:
  - scripts/_apply_ombre_quizzes.py  (attaches per-lesson quizzes to the LIVE
    Ombré course without re-seeding, so videos are preserved), and
  - (optionally) the canonical seed for future re-seeds.

Each quiz maps to one lesson of the Ombré course by (chapter title, lesson
title) — these MUST match the seeded titles exactly. Every question is a
single-answer MCQ (4 options). Q() builds the {question,type,options} shape the
seed's create_quiz expects.
"""


def Q(question, a, b, c, d, correct):
    """Build a single-choice MCQ. `correct` is one of 'A','B','C','D'."""
    letters = ["A", "B", "C", "D"]
    opts = [a, b, c, d]
    return {
        "question": question,
        "type": "SingleChoice",
        "options": [
            {"option": o, "is_correct": 1 if letters[i] == correct else 0}
            for i, o in enumerate(opts)
        ],
    }


OMBRE_QUIZZES = [
    # ===================== Chapter 1 =====================
    {
        "chapter": "Skin Anatomy & Healing Science",
        "lesson": "Introduction & Skin Anatomy",
        "title": "Ombré — Skin Anatomy Quiz",
        "questions": [
            Q("What are the three main layers of the skin?", "Epidermis, Dermis, Hypodermis", "Dermis, Muscle, Fat", "Epidermis, Muscle, Bone", "Fat, Bone, Tissue", "A"),
            Q("Which skin layer is the outermost layer?", "Dermis", "Hypodermis", "Epidermis", "Subcutaneous layer", "C"),
            Q("In which layer is pigment (melanin) primarily found?", "Dermis", "Hypodermis", "Epidermis", "Muscle layer", "C"),
            Q("Which layer contains collagen and elastin fibers?", "Epidermis", "Dermis", "Hypodermis", "Hair shaft", "B"),
            Q("Where should SPMU pigment ideally be implanted?", "Upper epidermis", "Mid-dermis", "Upper dermis", "Hypodermis", "C"),
            Q("What happens if pigment is implanted too deep?", "Fades quickly", "Becomes sharper", "May cause blurred or blue tones", "No change", "C"),
            Q("Which layer is responsible for skin regeneration?", "Stratum corneum", "Basal layer (stratum basale)", "Dermis", "Hypodermis", "B"),
            Q("What is the main function of the hypodermis?", "Produce melanin", "Provide cushioning and fat storage", "Regenerate skin", "Hold pigment", "B"),
            Q("Which structure is found in the dermis?", "Melanin only", "Hair follicles and glands", "Dead skin cells", "Keratin only", "B"),
            Q("Why is correct depth important in SPMU?", "For faster healing", "For better color retention and natural results", "To reduce cost", "To increase pain", "B"),
        ],
    },
    {
        "chapter": "Skin Anatomy & Healing Science",
        "lesson": "Fitzpatrick Skin Types",
        "title": "Ombré — Fitzpatrick Skin Types Quiz",
        "questions": [
            Q("What does the Fitzpatrick scale measure?", "Skin thickness", "Skin color and reaction to sun", "Hair growth", "Age", "B"),
            Q("How many Fitzpatrick skin types are there?", "4", "5", "6", "7", "C"),
            Q("Which skin type burns easily and never tans?", "Type I", "Type III", "Type V", "Type VI", "A"),
            Q("Which skin type is most common in Ethiopian clients?", "Type I", "Type II", "Type IV–V", "Type I–II", "C"),
            Q("Darker skin types have more of what?", "Collagen", "Melanin", "Fat", "Blood vessels", "B"),
            Q("Why is Fitzpatrick classification important in SPMU?", "To choose correct pigment color", "To determine price", "To reduce appointment time", "To select machine brand", "A"),
            Q("Which skin type has higher risk of hyperpigmentation?", "Type I", "Type II", "Type IV–VI", "Type I–III", "C"),
            Q("Which undertone is common in darker skin tones?", "Cool only", "Warm/red/orange", "Blue only", "Neutral only", "B"),
            Q("What happens if incorrect pigment is used on darker skin?", "Better results", "May turn ashy or grey", "Faster healing", "No effect", "B"),
            Q("Which Fitzpatrick type tans easily and rarely burns?", "Type I", "Type II", "Type IV", "Type I only", "C"),
        ],
    },
    {
        "chapter": "Skin Anatomy & Healing Science",
        "lesson": "Healing Science",
        "title": "Ombré — Healing Science Quiz",
        "questions": [
            Q("How many main stages are in skin healing?", "2", "3", "4", "5", "C"),
            Q("What is the first stage of healing?", "Proliferation", "Inflammation", "Maturation", "Pigmentation", "B"),
            Q("What happens during inflammation?", "Skin peels", "Body responds to injury and protects the area", "Pigment settles", "Hair grows", "B"),
            Q("What is the second stage of healing?", "Inflammation", "Proliferation", "Maturation", "Scabbing", "B"),
            Q("What happens during proliferation?", "Skin breaks", "New skin cells form", "Pigment disappears", "Blood stops flowing", "B"),
            Q("What is the final stage of healing?", "Proliferation", "Inflammation", "Maturation", "Bleeding", "C"),
            Q("Why do brows appear darker immediately after treatment?", "Pigment oxidizes", "Skin is swollen and pigment is fresh", "Healing is complete", "Color is incorrect", "B"),
            Q("What is normal during healing?", "Heavy bleeding", "Scabbing and flaking", "No change", "Permanent redness", "B"),
            Q("Why is proper aftercare important?", "To reduce cost", "To ensure proper healing and pigment retention", "To shorten procedure time", "To increase pain", "B"),
            Q("What can happen if a client picks scabs?", "Better retention", "Faster healing", "Pigment loss or patchiness", "No effect", "C"),
        ],
    },
    # ===================== Chapter 2 =====================
    {
        "chapter": "Hygiene & Infection Control Protocol",
        "lesson": "Hygiene Fundamentals",
        "title": "Ombré — Hygiene Fundamentals Quiz",
        "questions": [
            Q("What is hygiene in SPMU practice?", "Only cleaning the tools", "Maintaining cleanliness to prevent infection", "Using expensive products", "Wearing makeup", "B"),
            Q("What is the most important step before any procedure?", "Taking photos", "Washing hands", "Choosing pigment", "Talking to client", "B"),
            Q("How long should proper hand washing take?", "5 seconds", "10 seconds", "At least 20 seconds", "1 minute only", "C"),
            Q("What type of gloves should be used during SPMU procedures?", "Cotton gloves", "Disposable medical gloves", "Wool gloves", "Plastic bags", "B"),
            Q("When should gloves be changed?", "After each client", "When torn or contaminated", "Between different procedure steps", "All of the above", "D"),
            Q("What is cross-contamination?", "Mixing pigments", "Transfer of bacteria between surfaces", "Cleaning tools", "Skin healing", "B"),
            Q("Which item should always be single-use?", "Machine", "Chair", "Needles", "Light", "C"),
            Q("Why is workstation setup important?", "For decoration", "To maintain a sterile and organized environment", "To impress clients only", "To save time", "B"),
            Q("What should be used to clean surfaces?", "Water only", "Approved disinfectant", "Oil", "Tissue paper", "B"),
            Q("What is personal protective equipment (PPE)?", "Makeup kit", "Tools", "Protective items like gloves, masks, aprons", "Pigments", "C"),
            Q("Why should jewelry be removed before procedures?", "For fashion", "To prevent contamination", "To look professional", "No reason", "B"),
            Q("What is proper hygiene practice for tools?", "Reuse without cleaning", "Clean and disinfect or dispose", "Share between clients", "Wash once a week", "B"),
            Q("What should be done if a tool falls on the floor?", "Use it anyway", "Clean and disinfect before reuse", "Ignore it", "Wipe with tissue only", "B"),
            Q("What is the purpose of a clean workspace barrier (e.g., plastic wrap)?", "Decoration", "Prevent contamination", "Improve lighting", "Reduce cost", "B"),
            Q("What is poor hygiene likely to cause?", "Better results", "Faster healing", "Infection and complications", "No effect", "C"),
        ],
    },
    {
        "chapter": "Hygiene & Infection Control Protocol",
        "lesson": "Infection Control Protocol",
        "title": "Ombré — Infection Control Quiz",
        "questions": [
            Q("What is infection control?", "Decorating the clinic", "Preventing spread of microorganisms", "Choosing pigments", "Skin analysis", "B"),
            Q("What are pathogens?", "Tools", "Harmful microorganisms", "Skin cells", "Pigments", "B"),
            Q("Which of the following is a bloodborne pathogen?", "Water", "Hepatitis B", "Air", "Oil", "B"),
            Q("What is sterilization?", "Cleaning visible dirt", "Killing all microorganisms", "Washing hands", "Using gloves", "B"),
            Q("What is disinfection?", "Killing some microorganisms on surfaces", "Killing all microorganisms", "Removing pigment", "Drying tools", "A"),
            Q("Which method is used for full sterilization?", "Alcohol wipe", "Autoclave", "Water rinse", "Tissue wipe", "B"),
            Q("What should be done with used needles?", "Throw in normal trash", "Reuse after cleaning", "Dispose in sharps container", "Wash and store", "C"),
            Q("What is a sharps container used for?", "Storing pigments", "Holding clean tools", "Safe disposal of needles and sharp items", "Mixing colors", "C"),
            Q("When should surfaces be disinfected?", "Once a day", "After each client", "Once a week", "Only when dirty", "B"),
            Q("What is PPE used for in infection control?", "Decoration", "Protect both artist and client", "Speed up work", "Reduce cost", "B"),
            Q("What should you do if exposed to blood?", "Ignore it", "Follow exposure protocol immediately", "Continue working", "Wash later", "B"),
            Q("Why is proper waste disposal important?", "For cleanliness only", "To prevent infection and contamination", "To reduce cost", "No reason", "B"),
            Q("What is considered a biohazard?", "Clean towel", "Blood-contaminated waste", "Water", "Cotton pad unused", "B"),
            Q("What is the safest practice for pigment use?", "Double dipping", "Using shared containers", "Using disposable pigment cups", "Reusing leftover pigment", "C"),
            Q("What is the goal of infection control in SPMU?", "Faster procedures", "Client satisfaction only", "Prevent disease transmission", "Reduce pigment use", "C"),
        ],
    },
    # ===================== Chapter 3 =====================
    {
        "chapter": "Color Theory & Pigment Selection",
        "lesson": "Color Theory",
        "title": "Ombré — Color Theory Quiz",
        "questions": [
            Q("What are the primary colors?", "Red, Blue, Yellow", "Green, Orange, Purple", "Black, White, Grey", "Brown, Beige, Pink", "A"),
            Q("What are secondary colors?", "Primary colors mixed together", "Natural colors", "Skin tones", "Neutral colors", "A"),
            Q("Which of the following is a secondary color?", "Red", "Blue", "Orange", "Yellow", "C"),
            Q("What happens when complementary colors are mixed?", "They brighten", "They neutralize each other", "They become darker only", "No change", "B"),
            Q("Which colors are considered warm tones?", "Blue, Green, Purple", "Red, Orange, Yellow", "Black and White", "Grey tones", "B"),
            Q("Which colors are considered cool tones?", "Red, Orange", "Yellow, Brown", "Blue, Green, Purple", "Beige tones", "C"),
            Q("What is the purpose of color correction in SPMU?", "To darken brows", "To fix unwanted tones", "To speed up procedure", "To reduce cost", "B"),
            Q("Which color is used to neutralize blue/grey brows?", "Green", "Orange", "Purple", "Blue", "B"),
            Q("Which color neutralizes red tones?", "Yellow", "Green", "Orange", "Blue", "B"),
            Q("What is undertone in skin?", "Surface color only", "Hidden tone beneath the skin", "Hair color", "Skin thickness", "B"),
            Q("Why is undertone important in SPMU?", "For decoration", "To choose correct pigment and avoid unwanted color shifts", "To reduce time", "To change face shape", "B"),
            Q("What may happen if color theory is ignored?", "Better results", "Natural finish", "Unwanted tones like grey, red, or blue", "Faster healing", "C"),
            Q("What is a neutral color?", "A mix of warm and cool tones", "Only warm color", "Only cool color", "Only black", "A"),
            Q("Which factor affects color results in skin?", "Skin type", "Depth of implantation", "Undertone", "All of the above", "D"),
            Q("What happens when pigment is implanted too deep (color-wise)?", "Becomes lighter", "Can turn blue/grey", "Turns red", "No change", "B"),
        ],
    },
    {
        "chapter": "Color Theory & Pigment Selection",
        "lesson": "Pigment Selection",
        "title": "Ombré — Pigment Selection Quiz",
        "questions": [
            Q("What is the main goal of pigment selection?", "Choose the darkest color", "Match client's skin tone and desired result", "Use trendy colors", "Use any available pigment", "B"),
            Q("What should be considered before selecting pigment?", "Skin type", "Undertone", "Natural brow hair", "All of the above", "D"),
            Q("What is pigment undertone?", "Brand name", "Hidden color base (warm, cool, neutral)", "Price", "Thickness", "B"),
            Q("Why are warm pigments often used in SPMU?", "They are cheaper", "They prevent ashy or grey healing", "They last longer only", "They are brighter", "B"),
            Q("What can happen if a cool pigment is used on cool undertone skin?", "Natural result", "May turn grey or ashy", "Turns red", "Fades immediately", "B"),
            Q("What is pigment oxidation?", "Mixing pigments", "Chemical change of pigment over time", "Cleaning pigment", "Storing pigment", "B"),
            Q("What affects pigment retention?", "Skin type", "Aftercare", "Technique", "All of the above", "D"),
            Q("Why should pigment not be reused?", "Color fades", "Risk of contamination", "Too expensive", "No reason", "B"),
            Q("What is the safest way to use pigment during procedure?", "Use directly from bottle", "Use disposable pigment cups", "Share between clients", "Mix with water", "B"),
            Q("How do oily skin types affect pigment?", "Better retention", "May cause faster fading", "No effect", "Makes color darker", "B"),
            Q("What should be done before applying pigment?", "Guess the color", "Analyze skin and client preference", "Use darkest shade", "Skip consultation", "B"),
            Q("Why is patch testing sometimes recommended?", "For decoration", "To check allergic reaction", "To save time", "To darken color", "B"),
            Q("What is the result of over-saturated pigment?", "Natural look", "Blurry or unnatural results", "Faster healing", "No effect", "B"),
            Q("What is a good practice when unsure about pigment choice?", "Use random color", "Choose lighter and build gradually", "Always go dark", "Skip procedure", "B"),
            Q("What defines a successful pigment result?", "Dark color only", "Balanced, natural, and healed tone matching client", "Bright color", "Trendy shade", "B"),
        ],
    },
    # ===================== Chapter 4 =====================
    {
        "chapter": "Face Shape & Brow Mapping",
        "lesson": "Face Shapes & Brow Design",
        "title": "Ombré — Face Shape & Brow Design Quiz",
        "questions": [
            Q("What is the purpose of brow design?", "To follow trends only", "To enhance facial harmony", "To make brows darker", "To reduce procedure time", "B"),
            Q("Which face shape is considered the most balanced?", "Square", "Round", "Oval", "Heart", "C"),
            Q("What brow shape suits a round face best?", "Flat brow", "High arch brow", "Curved brow only", "Thin brow", "B"),
            Q("What brow shape is ideal for a square face?", "Sharp arch", "Soft rounded brow", "Flat brow", "Very thin brow", "B"),
            Q("What brow style suits a long face?", "High arch", "Flat/straight brow", "Thin brow", "Curved only", "B"),
            Q("What brow shape complements a heart-shaped face?", "Flat brow", "Soft arch", "Sharp angled brow", "Straight thick brow", "B"),
            Q("Why is face shape analysis important?", "For decoration", "To create symmetry and balance", "To increase cost", "To reduce time", "B"),
            Q("What should NOT influence brow design?", "Client's natural features", "Face shape", "Random trends only", "Bone structure", "C"),
            Q("What is the key goal of brow design?", "Make brows identical", "Enhance natural beauty", "Follow one standard shape", "Copy celebrities", "B"),
            Q("What happens if face shape is ignored?", "Better results", "Unbalanced appearance", "Faster healing", "No effect", "B"),
        ],
    },
    {
        "chapter": "Face Shape & Brow Mapping",
        "lesson": "The Golden Ratio Mapping System",
        "title": "Ombré — Golden Ratio Mapping Quiz",
        "questions": [
            Q("What is the Golden Ratio?", "Random measurement", "Mathematical proportion for balance and symmetry", "Skin type", "Pigment ratio", "B"),
            Q("What is the approximate value of the Golden Ratio (Phi)?", "1.0", "1.2", "1.618", "2.0", "C"),
            Q("What does the Golden Ratio help achieve in brows?", "Darker color", "Balanced and symmetrical design", "Faster procedure", "Less pigment use", "B"),
            Q("Where should the brow start point align?", "Nose wing straight up", "Eye corner", "Forehead", "Ear", "A"),
            Q("Where is the highest point of the arch located?", "Above pupil", "Above outer eye corner", "Middle of forehead", "End of brow", "A"),
            Q("Where should the brow tail end?", "Middle of eye", "Outer corner of eye and nose alignment", "Nose only", "Ear line", "B"),
            Q("What tool is commonly used for mapping?", "Pencil", "Thread", "Ruler", "All of the above", "D"),
            Q("Why is precise mapping important?", "For decoration", "To ensure symmetry and accuracy", "To save time only", "No reason", "B"),
            Q("What happens if mapping is incorrect?", "Perfect brows", "Asymmetrical results", "Faster healing", "Better retention", "B"),
            Q("Mapping should be done before what step?", "Aftercare", "Pigment selection", "Procedure begins", "Healing", "C"),
        ],
    },
    {
        "chapter": "Face Shape & Brow Mapping",
        "lesson": "Personalization & Facial Asymmetry Correction",
        "title": "Ombré — Asymmetry Correction Quiz",
        "questions": [
            Q("Are human faces perfectly symmetrical?", "Yes", "No", "Sometimes", "Only in photos", "B"),
            Q("What is asymmetry in brows?", "Identical brows", "Uneven shape, height, or thickness", "Dark color", "Straight lines", "B"),
            Q("What is the goal when correcting asymmetry?", "Make brows identical", "Create visual balance", "Change face completely", "Follow trends", "B"),
            Q("Why should over-correction be avoided?", "It wastes time", "It can look unnatural", "It is expensive", "No reason", "B"),
            Q("What should be considered in personalization?", "Client preference", "Face shape", "Natural brow growth", "All of the above", "D"),
            Q("What is the role of client consultation in design?", "Optional", "Essential for personalization", "Only for payment", "Not important", "B"),
            Q("What happens if asymmetry is ignored?", "Better result", "More balanced look", "Noticeable uneven brows", "No effect", "C"),
            Q("What technique helps correct uneven brows?", "Guessing", "Careful mapping and adjustment", "Using darker pigment", "Skipping design", "B"),
            Q("What should guide final brow design?", "Trend only", "Client's unique features", "Artist preference only", "Random choice", "B"),
            Q("What defines a successful personalized brow?", "Same for everyone", "Enhances individual beauty", "Very dark", "Very thin", "B"),
        ],
    },
    {
        "chapter": "Face Shape & Brow Mapping",
        "lesson": "Mapping Tools & Pre-Drawing Process",
        "title": "Ombré — Mapping Tools Quiz",
        "questions": [
            Q("What is pre-drawing?", "Final tattoo", "Sketching brow shape before procedure", "Cleaning skin", "Applying pigment", "B"),
            Q("Why is pre-drawing important?", "Saves pigment", "Allows correction before tattooing", "Reduces cost", "Speeds healing", "B"),
            Q("What tool is commonly used for pre-drawing?", "Pigment", "Pencil/marker", "Needle", "Machine", "B"),
            Q("What should be done after pre-drawing?", "Start immediately", "Show client and get approval", "Remove drawing", "Ignore it", "B"),
            Q("What is the purpose of mapping string/thread?", "Decoration", "Create straight, precise lines", "Clean skin", "Apply pigment", "B"),
            Q("What happens if pre-drawing is skipped?", "Better design", "Risk of incorrect brow shape", "Faster result", "No effect", "B"),
            Q("What should be checked during mapping?", "Symmetry", "Proportions", "Alignment", "All of the above", "D"),
            Q("What is a caliper used for?", "Coloring", "Measuring brow proportions", "Cleaning", "Tattooing", "B"),
            Q("Why is client approval critical before starting?", "For legal and satisfaction reasons", "To save time", "To reduce pigment", "Not necessary", "A"),
            Q("What defines a perfect mapping process?", "Fast drawing", "Accurate, symmetrical, and approved design", "Dark lines", "Trendy shape", "B"),
        ],
    },
    # ===================== Chapter 5 =====================
    {
        "chapter": "Machine & Needle Knowledge",
        "lesson": "Machine & Needle Knowledge",
        "title": "Ombré — Machine & Needle Quiz",
        "questions": [
            Q("What is the purpose of an SPMU machine?", "Clean skin", "Implant pigment into the skin", "Draw brows only", "Remove pigment", "B"),
            Q("Which type of machine is most commonly used in modern SPMU?", "Coil machine", "Rotary pen machine", "Manual blade only", "Laser machine", "B"),
            Q("What controls the needle movement in the machine?", "Grip", "Motor", "Cartridge", "Cable", "B"),
            Q("What is a needle cartridge?", "Machine body", "Disposable needle unit", "Power source", "Pigment container", "B"),
            Q("Why are cartridges preferred in SPMU?", "Cheaper", "Reusable", "Hygienic and disposable", "Larger", "C"),
            Q("What does needle configuration refer to?", "Machine speed", "Arrangement and number of needles", "Color of needle", "Length of machine", "B"),
            Q("Which needle type is commonly used for shading (ombre brows)?", "Single needle", "Round shader (RS)", "Flat needle only", "Blade", "B"),
            Q("What is a single needle (1RL) used for?", "Shading large areas", "Creating fine lines and detail", "Cleaning skin", "Blending pigment", "B"),
            Q("What does RL stand for?", "Round Liner", "Rapid Line", "Rotary Line", "Regular Line", "A"),
            Q("What does RS stand for?", "Round Stroke", "Round Shader", "Rotary Shade", "Rapid Shade", "B"),
            Q("Where should pigment be implanted?", "Epidermis only", "Upper dermis", "Hypodermis", "Muscle", "B"),
            Q("What happens if the needle goes too deep?", "Better retention", "Blowout or blurred pigment", "Faster healing", "No effect", "B"),
            Q("What happens if the needle is too shallow?", "Strong color", "Pigment fades quickly", "Perfect result", "Darker brows", "B"),
            Q("What controls needle depth?", "Machine only", "Hand pressure and machine setting", "Pigment color", "Light", "B"),
            Q("What is the ideal hand movement in ombre brows?", "Heavy pressure", "Soft, controlled shading motion", "Fast scratching", "Hard pressing", "B"),
            Q("What angle is typically used for machine work?", "90°", "45°–60°", "10°", "Flat 0°", "B"),
            Q("Why is consistent depth important?", "For speed", "For even color and healing", "For cost", "No reason", "B"),
            Q("What is \"blowout\" in SPMU?", "Perfect shading", "Pigment spreading under the skin", "Light color", "Skin dryness", "B"),
            Q("What causes trauma to the skin?", "Light pressure", "Excessive pressure and repeated passes", "Proper technique", "Good hygiene", "B"),
            Q("What is the goal of correct needle control?", "Faster work", "Safe, even pigment implantation", "Darker brows", "Less effort", "B"),
            Q("What does machine speed (voltage) affect?", "Pigment color", "Needle movement speed", "Skin type", "Brow shape", "B"),
            Q("What happens if machine speed is too high?", "Better control", "More trauma to skin", "Slower work", "No change", "B"),
            Q("What happens if machine speed is too low?", "Better saturation", "Poor pigment implantation", "Faster results", "Darker color", "B"),
            Q("Why should machines be covered with barrier film?", "Decoration", "Prevent contamination", "Improve grip", "Reduce cost", "B"),
            Q("What should be checked before starting the machine?", "Battery only", "Needle fit and function", "Client makeup", "Lighting", "B"),
            Q("What is the correct way to handle cartridges?", "Reuse", "Use sterile and dispose after one use", "Clean and reuse", "Share between clients", "B"),
            Q("Why is machine maintenance important?", "For appearance", "For safety and performance", "For branding", "No reason", "B"),
            Q("What should be done after procedure with machine setup?", "Leave as is", "Remove barriers and disinfect", "Store immediately", "Ignore cleaning", "B"),
            Q("What is the safest practice when unsure about a setting?", "Guess", "Start low and adjust carefully", "Use highest setting", "Skip procedure", "B"),
            Q("What defines professional machine use?", "Fast work", "Safe, controlled, hygienic technique", "Expensive equipment only", "Trend-based work", "B"),
        ],
    },
    # ===================== Chapter 6 =====================
    {
        "chapter": "Types of Brow Techniques",
        "lesson": "Ombré Brows",
        "title": "Ombré — Ombré Brows Quiz",
        "questions": [
            Q("What defines ombré brows?", "Hair strokes only", "Gradient shading effect", "Solid dark block", "No pigment", "B"),
            Q("Where is the lightest part of ombré brows?", "Tail", "Middle", "Front", "Arch", "C"),
            Q("Where is the darkest part of ombré brows?", "Front", "Tail", "Middle", "Head only", "B"),
            Q("Which technique is used for ombré brows?", "Hair stroke technique", "Machine shading", "Blade only", "Laser", "B"),
            Q("What is the main advantage of ombré brows?", "Permanent bold look only", "Soft, natural makeup effect", "No healing", "No fading", "B"),
            Q("Which skin type is most suitable for ombré brows?", "Oily skin", "Dry skin", "All skin types", "Sensitive only", "C"),
            Q("What happens if shading is too heavy?", "Better gradient", "Blocky unnatural brows", "Faster healing", "No effect", "B"),
        ],
    },
    {
        "chapter": "Types of Brow Techniques",
        "lesson": "Nano Brows",
        "title": "Ombré — Nano Brows Quiz",
        "questions": [
            Q("What are nano brows?", "Shading technique", "Machine-created hair strokes", "Tattoo removal", "Powder effect", "B"),
            Q("Which tool is used for nano brows?", "Blade", "Machine with fine needle", "Brush", "Razor", "B"),
            Q("What is the goal of nano brows?", "Bold makeup look", "Natural hair-like strokes", "Dark block brows", "Thick shading", "B"),
            Q("Who is the best candidate for nano brows?", "Very oily skin", "Clients wanting natural look", "Only mature clients", "Only dry skin", "B"),
            Q("What happens if strokes are too deep?", "Natural look", "Blurred strokes", "Light strokes", "Faster healing", "B"),
            Q("What needle type is commonly used?", "Round shader", "Single needle (1RL)", "Flat needle", "Blade", "B"),
        ],
    },
    {
        "chapter": "Types of Brow Techniques",
        "lesson": "Combo Brows",
        "title": "Ombré — Combo Brows Quiz",
        "questions": [
            Q("What are combo brows?", "Only shading", "Combination of hair strokes and shading", "Only microblading", "Tattoo removal", "B"),
            Q("Where are hair strokes usually placed?", "Tail", "Front", "Arch", "Entire brow", "B"),
            Q("Where is shading applied in combo brows?", "Front only", "Tail and body", "None", "Outside only", "B"),
            Q("Who are combo brows best for?", "Clients wanting both definition and natural look", "Clients with no brows only", "Children", "Oily skin only", "A"),
            Q("What is the risk of poor blending in combo brows?", "Better result", "Patchy or uneven appearance", "Faster healing", "No effect", "B"),
        ],
    },
    {
        "chapter": "Types of Brow Techniques",
        "lesson": "Powder Brows",
        "title": "Ombré — Powder Brows Quiz",
        "questions": [
            Q("What defines powder brows?", "Hair strokes", "Solid soft shaded makeup look", "No pigment", "Only front strokes", "B"),
            Q("How do powder brows differ from ombré brows?", "No difference", "More uniform shading", "Less pigment", "Only strokes", "B"),
            Q("Who are powder brows best suited for?", "Clients wanting bold makeup look", "Clients wanting no brows", "Children", "Sensitive skin only", "A"),
            Q("What happens if saturation is too heavy?", "Natural look", "Harsh and unnatural brows", "Faster healing", "No effect", "B"),
        ],
    },
    {
        "chapter": "Types of Brow Techniques",
        "lesson": "Artificial Skin Practice Drills",
        "title": "Ombré — Artificial Skin Practice Quiz",
        "questions": [
            Q("Why is artificial skin used in training?", "Decoration", "Practice before real clients", "Saving pigment", "Faster certification", "B"),
            Q("What skill is developed on artificial skin?", "Talking to clients", "Machine control and technique", "Payment handling", "Photography", "B"),
            Q("What should students focus on during practice?", "Speed only", "Consistency and control", "Color only", "Skipping steps", "B"),
            Q("When is a student ready for live model?", "After one practice", "After consistent results on artificial skin", "Immediately", "Never", "B"),
        ],
    },
    {
        "chapter": "Types of Brow Techniques",
        "lesson": "Client Consultation & Documentation",
        "title": "Ombré — Client Consultation Quiz",
        "questions": [
            Q("What is the purpose of client consultation?", "Payment only", "Understand client needs and suitability", "Decoration", "Speed", "B"),
            Q("What should be discussed during consultation?", "Desired result", "Skin condition", "Medical history", "All of the above", "D"),
            Q("Why is documentation important?", "For decoration", "Legal and professional record", "Reduce time", "Optional", "B"),
            Q("What must a client sign before procedure?", "Receipt", "Consent form", "Business card", "None", "B"),
            Q("What should be taken before procedure?", "Payment only", "Before photos", "Aftercare only", "Nothing", "B"),
            Q("What happens if consultation is skipped?", "Better results", "Risk of dissatisfaction or complications", "Faster work", "No effect", "B"),
            Q("What defines a professional consultation?", "Quick discussion", "Detailed, clear, and documented process", "No questions", "Only pricing", "B"),
        ],
    },
    # ===================== Chapter 7 =====================
    {
        "chapter": "Live Demo Procedures",
        "lesson": "Live Model Procedure Guide",
        "title": "Ombré — Live Model Procedure Quiz",
        "questions": [
            Q("What is the purpose of a live model procedure?", "Practice only", "Apply skills on a real client under supervision", "Decoration", "Testing equipment", "B"),
            Q("What must be completed before starting the procedure?", "Payment only", "Consultation, consent, and mapping", "Only pigment selection", "Nothing", "B"),
            Q("What is the first step before touching the client?", "Start machine", "Wash hands and wear PPE", "Choose pigment", "Take photos", "B"),
            Q("Why is skin analysis important before procedure?", "For decoration", "To choose correct technique and pigment", "To reduce time", "No reason", "B"),
            Q("What should be done before pigment implantation?", "Start immediately", "Pre-draw and get client approval", "Skip mapping", "Apply pigment directly", "B"),
            Q("What is the correct hygiene practice during procedure?", "Reuse tools", "Maintain sterile and clean environment", "Touch multiple surfaces", "Skip gloves", "B"),
            Q("What should be monitored during procedure?", "Only time", "Client comfort and skin response", "Music", "Lighting only", "B"),
            Q("What is the correct response if excessive bleeding occurs?", "Ignore it", "Stop and assess technique/depth", "Continue faster", "Add more pigment", "B"),
            Q("What indicates correct technique?", "Heavy bleeding", "Smooth, even pigment implantation", "Painful process", "Fast procedure", "B"),
            Q("What should be avoided during procedure?", "Gentle movement", "Overworking the skin", "Hygiene", "Mapping", "B"),
            Q("Why is client communication important during procedure?", "For entertainment", "To ensure comfort and trust", "Not important", "To reduce time", "B"),
            Q("What should be done immediately after procedure?", "Send client home", "Clean area and apply aftercare instructions", "Start next client", "Ignore", "B"),
            Q("What documentation should be completed after procedure?", "None", "Procedure notes and photos", "Only payment record", "Only consent", "B"),
            Q("Why are before-and-after photos important?", "Decoration", "Record results and progress", "Optional", "Only for social media", "B"),
            Q("What defines a successful live procedure?", "Fast completion", "Safe, hygienic, and balanced result", "Dark color only", "No client feedback", "B"),
        ],
    },
    {
        "chapter": "Live Demo Procedures",
        "lesson": "Healing & Touch-Up Protocol",
        "title": "Ombré — Healing & Touch-Up Quiz",
        "questions": [
            Q("How long does initial healing typically take?", "1–2 days", "7–14 days", "1 month", "3 months", "B"),
            Q("What is normal during healing?", "No change", "Scabbing and flaking", "Permanent redness", "Bleeding", "B"),
            Q("Why do brows appear darker after procedure?", "Wrong pigment", "Fresh pigment and skin reaction", "Healing complete", "Oxidation only", "B"),
            Q("What happens during peeling phase?", "Skin grows thicker", "Pigment may appear lighter temporarily", "Color becomes darker", "No change", "B"),
            Q("Why should clients avoid picking scabs?", "No reason", "Prevent pigment loss and scarring", "Faster healing", "Better color", "B"),
            Q("What is the purpose of aftercare?", "Decoration", "Ensure proper healing and retention", "Reduce cost", "Speed up procedure", "B"),
            Q("When is a touch-up usually scheduled?", "Immediately", "4–8 weeks after procedure", "1 year later", "Next day", "B"),
            Q("Why is a touch-up needed?", "To fix uneven areas and enhance color", "To redo entire procedure", "Optional only", "No reason", "A"),
            Q("What affects healing results?", "Skin type", "Aftercare", "Technique", "All of the above", "D"),
            Q("What should clients avoid during healing?", "Water", "Excess moisture, sweating, and sun exposure", "Sleeping", "Eating", "B"),
            Q("What is a common mistake during healing?", "Following aftercare", "Touching or picking brows", "Cleaning gently", "Avoiding sun", "B"),
            Q("What indicates healed results?", "Dark thick brows", "Soft, natural, settled color", "Red skin", "Flaking", "B"),
            Q("What should be done if uneven healing occurs?", "Ignore", "Correct during touch-up", "Start over immediately", "Apply more pigment at home", "B"),
            Q("What defines good pigment retention?", "Very dark brows", "Even, long-lasting color", "No fading", "Thick lines", "B"),
            Q("What defines a successful final result?", "Immediate appearance only", "Healed, balanced, natural-looking brows", "Darkest possible color", "No touch-up needed", "B"),
        ],
    },
    # ===================== Chapter 8 =====================
    {
        "chapter": "Business & Branding Fundamentals",
        "lesson": "Business & Branding",
        "title": "Ombré — Business & Branding Quiz",
        "questions": [
            Q("What is branding?", "Logo only", "Overall identity and perception of a business", "Price list", "Equipment", "B"),
            Q("What elements make up a brand?", "Logo, colors, tone, and client experience", "Price only", "Location only", "Tools only", "A"),
            Q("Why is branding important in SPMU?", "For decoration", "Builds trust and attracts clients", "Reduces work", "Not important", "B"),
            Q("What does a strong brand communicate?", "Confusion", "Professionalism and consistency", "Low quality", "Random style", "B"),
            Q("What should your brand reflect?", "Trends only", "Your values and style", "Competitors", "Random ideas", "B"),
            Q("Why is consistency important in branding?", "Saves time", "Builds recognition and trust", "Reduces cost", "No reason", "B"),
            Q("What is a target audience?", "Competitors", "Ideal clients you want to attract", "Friends only", "Random people", "B"),
            Q("What role does social media play in branding?", "None", "Major platform to showcase work and attract clients", "Only for fun", "Optional only", "B"),
            Q("What type of content builds trust?", "Random posts", "Before-and-after results and educational content", "Only selfies", "No posts", "B"),
            Q("What is a brand voice?", "Music", "Communication style of your business", "Logo", "Color", "B"),
            Q("What is the purpose of a logo?", "Decoration only", "Visual representation of the brand", "Pricing tool", "Equipment", "B"),
            Q("What builds client trust the most?", "Low prices", "Professional results and consistency", "Fast service", "Trends", "B"),
            Q("What is a unique selling point (USP)?", "Price", "What makes your business different", "Location", "Equipment", "B"),
            Q("Why is client experience part of branding?", "Not important", "It shapes how clients remember your business", "Only for reviews", "Only for payment", "B"),
            Q("What defines a luxury brand in SPMU?", "Expensive tools only", "High-quality service, experience, and consistency", "Dark colors", "Fast service", "B"),
        ],
    },
    {
        "chapter": "Business & Branding Fundamentals",
        "lesson": "Common Beginner Mistakes",
        "title": "Ombré — Common Beginner Mistakes Quiz",
        "questions": [
            Q("What is a common beginner mistake in SPMU?", "Practicing", "Overworking the skin", "Learning theory", "Using hygiene", "B"),
            Q("What happens if skin is overworked?", "Better results", "Trauma and poor healing", "Faster healing", "No effect", "B"),
            Q("What is a mistake in pigment application?", "Light layering", "Over-saturation", "Gradual build-up", "Correct technique", "B"),
            Q("What happens if mapping is skipped?", "Perfect brows", "Uneven and unbalanced results", "Faster work", "No effect", "B"),
            Q("What is a business mistake beginners make?", "Building brand", "Inconsistent social media presence", "Learning", "Practicing", "B"),
            Q("Why is copying other artists a mistake?", "Saves time", "Prevents building unique identity", "Improves skill", "No effect", "B"),
            Q("What is a mistake in client consultation?", "Asking questions", "Skipping consultation", "Listening to client", "Documenting", "B"),
            Q("What happens if aftercare is not explained?", "Better results", "Poor healing and dissatisfaction", "Faster healing", "No effect", "B"),
            Q("What is a mistake in pricing?", "Fair pricing", "Underpricing services", "Charging for quality", "Clear pricing", "B"),
            Q("Why is rushing the procedure a mistake?", "Saves time", "Reduces quality and safety", "Improves results", "No effect", "B"),
            Q("What is a mistake in hygiene practice?", "Using PPE", "Reusing disposable items", "Cleaning tools", "Disinfecting", "B"),
            Q("What is a mistake in learning?", "Practicing on artificial skin", "Skipping fundamentals", "Studying theory", "Asking questions", "B"),
            Q("What is a mistake in client expectations?", "Clear communication", "Overpromising results", "Honest explanation", "Showing examples", "B"),
            Q("What is a mistake in portfolio building?", "Posting results", "Editing photos unrealistically", "Showing real work", "Documenting progress", "B"),
            Q("What defines a successful beginner artist?", "Fast work", "Continuous learning and safe practice", "Copying others", "Cheap pricing", "B"),
        ],
    },
]
