import { Link, useNavigate, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { BookOpen, CheckCircle, ChevronLeft, Package } from 'lucide-react';
import { getBundleDetail } from '@/api/client';
import type { CourseBundle } from '@/types';
import { formatPrice } from '@/lib/utils';

export default function BundleDetail() {
  const { bundleId } = useParams<{ bundleId: string }>(); const navigate = useNavigate();
  const { data, isLoading, isError } = useQuery({ queryKey: ['bundle', bundleId], queryFn: () => getBundleDetail(bundleId!), enabled: !!bundleId });
  const bundle = data as CourseBundle | undefined;
  if (isLoading) return <div className="min-h-screen flex justify-center items-center text-gray-500">Loading bundle…</div>;
  if (isError || !bundle) return <div className="min-h-screen flex flex-col gap-3 justify-center items-center"><p>Bundle not found.</p><Link to="/courses" className="text-primary">Browse courses</Link></div>;
  return <div className="min-h-screen bg-alabaster"><div className="max-w-6xl mx-auto px-4 sm:px-6 py-8"><button onClick={() => navigate(-1)} className="text-sm text-gray-500 flex gap-1 items-center mb-6"><ChevronLeft className="w-4 h-4" /> Back</button><div className="grid lg:grid-cols-[1.4fr_.8fr] gap-8"><section><img src={bundle.image || '/placeholder-course.svg'} alt="" className="w-full aspect-video object-cover rounded-2xl bg-primary/10" /><div className="mt-6 flex items-center gap-2 text-primary text-xs uppercase tracking-widest font-semibold"><Package className="w-4 h-4" /> Course bundle</div><h1 className="font-heading text-3xl font-bold text-dark mt-2">{bundle.title}</h1><p className="text-gray-600 mt-4 whitespace-pre-line">{bundle.description}</p><h2 className="font-heading text-xl font-semibold mt-8 mb-4">Included courses</h2><div className="space-y-3">{bundle.courses.map(course => <Link key={course.name} to={`/course/${course.name}`} className="flex gap-3 bg-white border rounded-xl p-3 hover:border-primary"><img src={course.image || '/placeholder-course.svg'} alt="" className="w-20 h-14 rounded object-cover bg-gray-100" /><div><p className="font-medium text-dark">{course.title}</p><p className="text-sm text-gray-500 line-clamp-1">{course.short_introduction}</p></div></Link>)}</div></section><aside className="h-fit bg-white border rounded-2xl p-6 lg:sticky lg:top-24"><p className="text-sm text-gray-500">One purchase gives access to</p><p className="font-semibold text-dark mt-1">{bundle.course_count} complete courses</p><div className="mt-5 flex items-baseline gap-2">{bundle.original_price && <span className="text-gray-400 line-through text-sm">{formatPrice(bundle.original_price, bundle.currency)}</span>}<span className="font-heading text-2xl font-bold text-primary">{formatPrice(bundle.price, bundle.currency)}</span></div>{bundle.discount_percentage > 0 && <p className="text-sm text-green-700 mt-1">{bundle.discount_percentage}% off</p>}<Link to={`/payment/bundle:${bundle.name}`} className="mt-5 w-full py-3 bg-dark text-white rounded-lg text-sm font-medium flex items-center justify-center gap-2 hover:bg-primary/90"><BookOpen className="w-4 h-4" /> Buy bundle</Link><p className="mt-4 text-xs text-gray-500 flex gap-2"><CheckCircle className="w-4 h-4 text-primary shrink-0" />Access to every included course for 30 days.</p></aside></div></div></div>;
}
